[package]
name = "surfjudge-actix"
version = "0.1.0"
authors = ["Dario Götz <dario.goetz@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^3.0.0"
actix-rt = "^1.1.1"

sqlx = { version = "0.4.0-beta.1", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "chrono" ] }

chrono = { version="^0.4.15", features=[ "serde" ] }


anyhow = "^1.0.32"
config = "^0.10.1"
slog = "^2.5.2"
sloggers = "^1.0.1"
dotenv = "^0.15.0"
once_cell = "^1.4.1"

serde = { version="^1.0.0", features=[ "derive" ]}
