[package]
name = "surfjudge-actix"
version = "0.1.0"
authors = ["Dario Götz <dario.goetz@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^3.0.0"
actix-rt = "^1.1.1"
actix-files = "^0.4.0"
actix-cors = "^0.4.1"
actix-identity = "^0.3.1"

sqlx = { version = "^0.4.2", default-features = false, features = [ "runtime-actix-rustls", "macros", "postgres", "chrono", "json" ] }

tera = "1"
chrono = { version="^0.4.15", features=[ "serde" ] }
futures = "^0.3.13"
anyhow = "^1.0.32"
config = "^0.10.1"
slog = "^2.5.2"
sloggers = "^1.0.1"
dotenv = "^0.15.0"
once_cell = "^1.4.1"
rand = "^0.8.0"
dashmap = "^4.0.2"
oso = "^0.8.2"
bcrypt = "^0.9.0"
zmq = "^0.9.2"

serde = { version="^1.0.0", features=[ "derive" ]}
serde_json = "^1.0.0"
