[package]
name = "surfjudge-actix"
version = "0.1.0"
authors = ["Dario Götz <dario.goetz@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
config = "*"
slog = "*"
sloggers = "*"
dotenv = "*"
once_cell = "*"
serde = { version="1.0", features=["derive"]}
actix-rt = "*"
