version: "3"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=surfjudge2000
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: dario.goetz@googlemail.com
      PGADMIN_DEFAULT_PASSWORD: uiae
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres:pgsql-server"

volumes:
  pgdata:
  pgadmin-data:
