version: "3"

services:
  app:
    build: .
    image: surfjudge-pyramid
    restart: unless-stopped
    networks:
      - default
    environment:
      - APP_DATABASE_URL=postgresql://postgres:surfjudge2000@postgres:5432/postgres
      - APP_SERVERADDRESS=0.0.0.0:8081
      - APP_UISETTINGS_APIPATH=/public
      - APP_UISETTINGS_WEBSOCKETURL=wss://websocket.surfjudge.de

  nginx:
    image: nginx
    restart: unless-stopped
    # only open the following ports in case this service is the main entrypoint
    # on the server, in particular not in a docker-gen (jwilder) setup
    ports:
        - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/www/data/static:ro
      - ./templates/index.html:/www/data/index.html:ro

    networks:
      - default
 
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=surfjudge2000
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: dario.goetz@googlemail.com
      PGADMIN_DEFAULT_PASSWORD: uiae
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "postgres:postgres"

volumes:
  pgdata:
  pgadmin-data:
