debug = false
server_address = "127.0.0.1:8081"
template_dir = "templates"

[ui_settings]
websocket_url = "wss://websocket.surfjudge.de"

[database]
url = "postgresql://postgres:surfjudge2000@localhost:5432/postgres"
max_connections = 100
