debug = false
serveraddress = "127.0.0.1:8081"
templatedir = "templates"

[uisettings]
websocketurl = "wss://websocket.surfjudge.de"
apipath = "/public"

[database]
url = "postgresql://postgres:surfjudge2000@localhost:5432/postgres"
maxconnections = 100
