debug = false
server_address = "127.0.0.1:8081"
template_dir = "templates"

[api]
websocket_url = "wss://websocket.surfjudge.de"
public_path = "/public"

[database]
url = "postgresql://postgres:surfjudge2000@localhost:5432/postgres"
max_connections = 10

[auth]
rules_file = "config/auth_rules.polar"

[notifications]
