server_address = "127.0.0.1:8081"
template_dir = "templates"


[database]
url = "postgresql://postgres:surfjudge2000@localhost:5432/postgres"
max_connections = 10


[api]
websocket_url = "ws://localhost:8081/ws"

# serve public api endpoints
public_path = "/public"

# serve authentication api endpoints
# auth_path = "/auth"

# serve judging api endpoints
# judging_path = "/judging"

# serve admin api endpoints
# admin = "/admin"


[auth]
rules_file = "config/auth_rules.polar"


[notifications]
# connect to external notifier via ZMQ
# zmq_sender_address = "localhost:6545"

# start own zmq server for receiving notifications to be forwarded
# zmq_receiver_port = "6545"

# start own websocket server
# websocket_server_address = "/ws"